// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace bftradeline
{

    public class SampleResponse1
    {

        [JsonProperty("marketId")]
        public string MarketId { get; set; }

        [JsonProperty("isMarketDataDelayed")]
        public bool IsMarketDataDelayed { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("betDelay")]
        public int BetDelay { get; set; }

        [JsonProperty("bspReconciled")]
        public bool BspReconciled { get; set; }

        [JsonProperty("complete")]
        public bool Complete { get; set; }

        [JsonProperty("inplay")]
        public bool Inplay { get; set; }

        [JsonProperty("numberOfWinners")]
        public int NumberOfWinners { get; set; }

        [JsonProperty("numberOfRunners")]
        public int NumberOfRunners { get; set; }

        [JsonProperty("numberOfActiveRunners")]
        public int NumberOfActiveRunners { get; set; }

        [JsonProperty("lastMatchTime")]
        public string LastMatchTime { get; set; }

        [JsonProperty("totalMatched")]
        public double TotalMatched { get; set; }

        [JsonProperty("totalAvailable")]
        public double TotalAvailable { get; set; }

        [JsonProperty("crossMatching")]
        public bool CrossMatching { get; set; }

        [JsonProperty("runnersVoidable")]
        public bool RunnersVoidable { get; set; }

        [JsonProperty("version")]
        public long Version { get; set; }

        [JsonProperty("runners")]
        public Runner[] Runners { get; set; }
    }

}
