//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIConfigServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIConfigServiceReference.IAPIConfigService")]
    internal interface IAPIConfigService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/GetAPIConfigData", ReplyAction="http://tempuri.org/IAPIConfigService/GetAPIConfigDataResponse")]
        string GetAPIConfigData(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/GetAPIConfigData", ReplyAction="http://tempuri.org/IAPIConfigService/GetAPIConfigDataResponse")]
        System.Threading.Tasks.Task<string> GetAPIConfigDataAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/UpdateSession", ReplyAction="http://tempuri.org/IAPIConfigService/UpdateSessionResponse")]
        void UpdateSession(string session, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/UpdateSession", ReplyAction="http://tempuri.org/IAPIConfigService/UpdateSessionResponse")]
        System.Threading.Tasks.Task UpdateSessionAsync(string session, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/GetPoundRate", ReplyAction="http://tempuri.org/IAPIConfigService/GetPoundRateResponse")]
        string GetPoundRate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/GetPoundRate", ReplyAction="http://tempuri.org/IAPIConfigService/GetPoundRateResponse")]
        System.Threading.Tasks.Task<string> GetPoundRateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/SetPoundRate", ReplyAction="http://tempuri.org/IAPIConfigService/SetPoundRateResponse")]
        void SetPoundRate(string Poundrate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIConfigService/SetPoundRate", ReplyAction="http://tempuri.org/IAPIConfigService/SetPoundRateResponse")]
        System.Threading.Tasks.Task SetPoundRateAsync(string Poundrate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    internal interface IAPIConfigServiceChannel : APIConfigServiceReference.IAPIConfigService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    internal partial class APIConfigServiceClient : System.ServiceModel.ClientBase<APIConfigServiceReference.IAPIConfigService>, APIConfigServiceReference.IAPIConfigService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public APIConfigServiceClient() : 
                base(APIConfigServiceClient.GetDefaultBinding(), APIConfigServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUserServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIConfigServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(APIConfigServiceClient.GetBindingForEndpoint(endpointConfiguration), APIConfigServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIConfigServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(APIConfigServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIConfigServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(APIConfigServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APIConfigServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetAPIConfigData(int ID)
        {
            return base.Channel.GetAPIConfigData(ID);
        }
        
        public System.Threading.Tasks.Task<string> GetAPIConfigDataAsync(int ID)
        {
            return base.Channel.GetAPIConfigDataAsync(ID);
        }
        
        public void UpdateSession(string session, int ID)
        {
            base.Channel.UpdateSession(session, ID);
        }
        
        public System.Threading.Tasks.Task UpdateSessionAsync(string session, int ID)
        {
            return base.Channel.UpdateSessionAsync(session, ID);
        }
        
        public string GetPoundRate()
        {
            return base.Channel.GetPoundRate();
        }
        
        public System.Threading.Tasks.Task<string> GetPoundRateAsync()
        {
            return base.Channel.GetPoundRateAsync();
        }
        
        public void SetPoundRate(string Poundrate)
        {
            base.Channel.SetPoundRate(Poundrate);
        }
        
        public System.Threading.Tasks.Task SetPoundRateAsync(string Poundrate)
        {
            return base.Channel.SetPoundRateAsync(Poundrate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54524/Services/APIConfigService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return APIConfigServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUserServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return APIConfigServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUserServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserServices,
        }
    }
}
