//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTWeb.BettingServiceGrayHoundPlaceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BettingServiceGrayHoundPlaceReference.IBettingServiceGrayHoundPlace")]
    public interface IBettingServiceGrayHoundPlace {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundPlace/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundPlace/GetDataFromBetfairReadOnlyRespon" +
            "se")]
        void GetDataFromBetfairReadOnly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundPlace/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundPlace/GetDataFromBetfairReadOnlyRespon" +
            "se")]
        System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundPlace/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundPlace/GetCurrentMarketBookCricketRespo" +
            "nse")]
        void GetCurrentMarketBookCricket(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundPlace/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundPlace/GetCurrentMarketBookCricketRespo" +
            "nse")]
        System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBettingServiceGrayHoundPlaceChannel : GTWeb.BettingServiceGrayHoundPlaceReference.IBettingServiceGrayHoundPlace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettingServiceGrayHoundPlaceClient : System.ServiceModel.ClientBase<GTWeb.BettingServiceGrayHoundPlaceReference.IBettingServiceGrayHoundPlace>, GTWeb.BettingServiceGrayHoundPlaceReference.IBettingServiceGrayHoundPlace {
        
        public BettingServiceGrayHoundPlaceClient() {
        }
        
        public BettingServiceGrayHoundPlaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettingServiceGrayHoundPlaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceGrayHoundPlaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceGrayHoundPlaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDataFromBetfairReadOnly() {
            base.Channel.GetDataFromBetfairReadOnly();
        }
        
        public System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync() {
            return base.Channel.GetDataFromBetfairReadOnlyAsync();
        }
        
        public void GetCurrentMarketBookCricket(string Password) {
            base.Channel.GetCurrentMarketBookCricket(Password);
        }
        
        public System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password) {
            return base.Channel.GetCurrentMarketBookCricketAsync(Password);
        }
    }
}
