//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTWeb.BettingServiceGrayHoundWinReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BettingServiceGrayHoundWinReference.IBettingServiceGrayHoundWin")]
    public interface IBettingServiceGrayHoundWin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundWin/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundWin/GetDataFromBetfairReadOnlyResponse" +
            "")]
        void GetDataFromBetfairReadOnly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundWin/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundWin/GetDataFromBetfairReadOnlyResponse" +
            "")]
        System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundWin/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundWin/GetCurrentMarketBookCricketRespons" +
            "e")]
        void GetCurrentMarketBookCricket(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceGrayHoundWin/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceGrayHoundWin/GetCurrentMarketBookCricketRespons" +
            "e")]
        System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBettingServiceGrayHoundWinChannel : GTWeb.BettingServiceGrayHoundWinReference.IBettingServiceGrayHoundWin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettingServiceGrayHoundWinClient : System.ServiceModel.ClientBase<GTWeb.BettingServiceGrayHoundWinReference.IBettingServiceGrayHoundWin>, GTWeb.BettingServiceGrayHoundWinReference.IBettingServiceGrayHoundWin {
        
        public BettingServiceGrayHoundWinClient() {
        }
        
        public BettingServiceGrayHoundWinClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettingServiceGrayHoundWinClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceGrayHoundWinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceGrayHoundWinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDataFromBetfairReadOnly() {
            base.Channel.GetDataFromBetfairReadOnly();
        }
        
        public System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync() {
            return base.Channel.GetDataFromBetfairReadOnlyAsync();
        }
        
        public void GetCurrentMarketBookCricket(string Password) {
            base.Channel.GetCurrentMarketBookCricket(Password);
        }
        
        public System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password) {
            return base.Channel.GetCurrentMarketBookCricketAsync(Password);
        }
    }
}
