//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAmount
    {
        public int id { get; set; }
        public Nullable<decimal> Debt { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Marketid { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Createdsate { get; set; }
        public string AccountTitle { get; set; }
    }
}
