//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BallbyBallSummary
    {
        public long ID { get; set; }
        public string EventID { get; set; }
        public string MarketID { get; set; }
        public Nullable<double> Overs { get; set; }
        public Nullable<int> Scores { get; set; }
        public Nullable<int> Innings { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> Wickets { get; set; }
        public string TeamName { get; set; }
        public string MatchStatus { get; set; }
        public string MatchType { get; set; }
        public string TotalOvers { get; set; }
    }
}
