//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetSlipKey
    {
        public int UserID { get; set; }
        public string SimpleBtn1 { get; set; }
        public string SimpleBtn2 { get; set; }
        public string SimpleBtn3 { get; set; }
        public string SimpleBtn4 { get; set; }
        public string SimpleBtn5 { get; set; }
        public string SimpleBtn6 { get; set; }
        public string SimpleBtn7 { get; set; }
        public string SimpleBtn8 { get; set; }
        public string SimpleBtn9 { get; set; }
        public string SimpleBtn10 { get; set; }
        public string SimpleBtn11 { get; set; }
        public string SimpleBtn12 { get; set; }
        public string MutipleBtn1 { get; set; }
        public string MutipleBtn2 { get; set; }
        public string MutipleBtn3 { get; set; }
        public string MutipleBtn4 { get; set; }
        public string MutipleBtn5 { get; set; }
        public string MutipleBtn6 { get; set; }
        public string MutipleBtn7 { get; set; }
        public string MutipleBtn8 { get; set; }
        public string MutipleBtn9 { get; set; }
        public string MutipleBtn10 { get; set; }
        public string MutipleBtn11 { get; set; }
        public string MutipleBtn12 { get; set; }
    }
}
