//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketCatalogueSelection
    {
        public string MarketCatalogueID { get; set; }
        public string SelectionID { get; set; }
        public string SelectionName { get; set; }
        public string JockeyName { get; set; }
        public string Wearing { get; set; }
        public string WearingDesc { get; set; }
        public string ClothNumber { get; set; }
        public string StallDraw { get; set; }
        public long ID { get; set; }
    }
}
