//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_ChangePasswordHistory
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public string OldPassword { get; set; }
        public int Updateby { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
