//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAmountHistory
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> AmountAdded { get; set; }
        public Nullable<int> AddedbyID { get; set; }
        public Nullable<System.DateTime> AmountAddedTime { get; set; }
        public Nullable<decimal> AmountRemoved { get; set; }
    }
}
