//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBet
    {
        public string SelectionID { get; set; }
        public string UserOdd { get; set; }
        public string Amount { get; set; }
        public string BetType { get; set; }
        public string LiveOdd { get; set; }
        public Nullable<bool> isMatched { get; set; }
        public string Status { get; set; }
        public string MarketBookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public long ID { get; set; }
        public string SelectionName { get; set; }
        public string MarketbookName { get; set; }
        public string AgentRate { get; set; }
        public string Liabality { get; set; }
        public string BetSize { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public string location { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<bool> TransferAdmin { get; set; }
        public Nullable<int> SuperAgentRateB { get; set; }
        public Nullable<int> TransferAgentIDB { get; set; }
        public Nullable<int> TransferAgentRateB { get; set; }
        public Nullable<int> PoundRateB { get; set; }
        public Nullable<int> TransferAdminPercentage { get; set; }
        public Nullable<int> SamiAdminRate { get; set; }
    }
}
