//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public long ID { get; set; }
        public string AccountsTitle { get; set; }
        public string Debit { get; set; }
        public string Credit { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MarketBookID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AgentRate { get; set; }
        public string ComissionRate { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<bool> isCreditAmount { get; set; }
        public string EventType { get; set; }
        public string WinnerName { get; set; }
        public string EventID { get; set; }
        public string EventName { get; set; }
        public string MareketBookNameAcc { get; set; }
        public string SuperRate { get; set; }
        public string SamiadminRate { get; set; }
    }
}
