//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.Services.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Location { get; set; }
        public string AccountBalance { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public int CreatedbyID { get; set; }
        public bool isDeleted { get; set; }
        public bool isBlocked { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string RatePercent { get; set; }
        public Nullable<bool> Loggedin { get; set; }
        public Nullable<decimal> StartBalance { get; set; }
        public Nullable<decimal> BetLowerLimit { get; set; }
        public decimal BetUpperLimit { get; set; }
        public bool CheckConditionsforPlacingBet { get; set; }
        public Nullable<bool> isHorseRaceAllowed { get; set; }
        public Nullable<bool> isGrayHoundRaceAllowed { get; set; }
        public Nullable<bool> isTennisAllowed { get; set; }
        public Nullable<bool> isSoccerAllowed { get; set; }
        public Nullable<decimal> BetLowerLimitHorsePlace { get; set; }
        public Nullable<decimal> BetUpperLimitHorsePlace { get; set; }
        public Nullable<decimal> BetUpperLimitGrayHoundPlace { get; set; }
        public Nullable<decimal> BetLowerLimitGrayHoundPlace { get; set; }
        public Nullable<decimal> BetUpperLimitGrayHoundWin { get; set; }
        public Nullable<decimal> BetLowerLimitGrayHoundWin { get; set; }
        public Nullable<decimal> BetUpperLimitMatchOdds { get; set; }
        public Nullable<decimal> BetLowerLimitMatchOdds { get; set; }
        public Nullable<decimal> BetUpperLimitInningRuns { get; set; }
        public Nullable<decimal> BetLowerLimitInningRuns { get; set; }
        public Nullable<decimal> BetUpperLimitCompletedMatch { get; set; }
        public Nullable<decimal> BetLowerLimitCompletedMatch { get; set; }
        public Nullable<int> CommissionRate { get; set; }
        public Nullable<decimal> BetUpperLimitMatchOddsSoccer { get; set; }
        public Nullable<decimal> BetLowerLimitMatchOddsSoccer { get; set; }
        public Nullable<decimal> BetUpperLimitMatchOddsTennis { get; set; }
        public Nullable<decimal> BetLowerLimitMatchOddsTennis { get; set; }
        public Nullable<decimal> BetUpperLimitTiedMatch { get; set; }
        public Nullable<decimal> BetLowerLimitTiedMatch { get; set; }
        public Nullable<decimal> BetUpperLimitWinner { get; set; }
        public Nullable<decimal> BetLowerLimitWinner { get; set; }
        public Nullable<decimal> MaxOddBack { get; set; }
        public Nullable<decimal> MaxOddLay { get; set; }
        public Nullable<bool> CheckforMaxOddBack { get; set; }
        public Nullable<bool> CheckforMaxOddLay { get; set; }
        public Nullable<long> CurrentLoggedInID { get; set; }
        public int ReferrerID { get; set; }
        public int ReferrerRate { get; set; }
        public bool isHorseRaceWinAllowedForBet { get; set; }
        public bool isGrayHoundRaceWinAllowedForBet { get; set; }
        public bool isTennisAllowedForBet { get; set; }
        public bool isSoccerAllowedForBet { get; set; }
        public bool isCricketMatchOddsAllowedForBet { get; set; }
        public bool isCricketInningsRunsAllowedForBet { get; set; }
        public bool isCricketTiedMatchAllowedForBet { get; set; }
        public bool isCricketCompletedMatchAllowedForBet { get; set; }
        public bool isHorseRacePlaceAllowedForBet { get; set; }
        public bool isGrayHoundRacePlaceAllowedForBet { get; set; }
        public int ParentID { get; set; }
        public bool isWinnerMarketAllowedForBet { get; set; }
        public bool isFancyMarketAllowed { get; set; }
        public Nullable<decimal> BetUpperLimitFancy { get; set; }
        public Nullable<decimal> BetLowerLimitFancy { get; set; }
        public Nullable<int> CommissionRateFancy { get; set; }
        public Nullable<bool> TransferAdminAmount { get; set; }
        public bool isBMSBlocked { get; set; }
        public Nullable<bool> TransferAgentCommission { get; set; }
        public Nullable<int> MaxBalanceTransferLimit { get; set; }
        public Nullable<int> MaxAgentRate { get; set; }
        public Nullable<int> SuperAgentID { get; set; }
        public Nullable<int> SuperAgentRate { get; set; }
        public Nullable<int> TransferAgentID { get; set; }
        public Nullable<int> TransferAgentRate { get; set; }
        public Nullable<bool> TransferAdminAmountSoccer { get; set; }
        public Nullable<bool> TransferAdminAmountTennis { get; set; }
        public Nullable<bool> TransferAdminAmountHorse { get; set; }
        public Nullable<bool> TransferAdminAmountGreyHound { get; set; }
        public Nullable<bool> isBetSlipKeysAllowed { get; set; }
        public Nullable<bool> isJoriBetAllowed { get; set; }
        public Nullable<int> TransferAdminPercentage { get; set; }
        public Nullable<bool> GTLogin { get; set; }
        public Nullable<bool> IsCom { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
