//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTWeb.BettingServiceHorseWinReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BettingServiceHorseWinReference.IBettingServiceHorseWin")]
    public interface IBettingServiceHorseWin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseWin/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceHorseWin/GetDataFromBetfairReadOnlyResponse")]
        void GetDataFromBetfairReadOnly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseWin/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceHorseWin/GetDataFromBetfairReadOnlyResponse")]
        System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseWin/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceHorseWin/GetCurrentMarketBookCricketResponse")]
        void GetCurrentMarketBookCricket(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseWin/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceHorseWin/GetCurrentMarketBookCricketResponse")]
        System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBettingServiceHorseWinChannel : GTWeb.BettingServiceHorseWinReference.IBettingServiceHorseWin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettingServiceHorseWinClient : System.ServiceModel.ClientBase<GTWeb.BettingServiceHorseWinReference.IBettingServiceHorseWin>, GTWeb.BettingServiceHorseWinReference.IBettingServiceHorseWin {
        
        public BettingServiceHorseWinClient() {
        }
        
        public BettingServiceHorseWinClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettingServiceHorseWinClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceHorseWinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceHorseWinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDataFromBetfairReadOnly() {
            base.Channel.GetDataFromBetfairReadOnly();
        }
        
        public System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync() {
            return base.Channel.GetDataFromBetfairReadOnlyAsync();
        }
        
        public void GetCurrentMarketBookCricket(string Password) {
            base.Channel.GetCurrentMarketBookCricket(Password);
        }
        
        public System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password) {
            return base.Channel.GetCurrentMarketBookCricketAsync(Password);
        }
    }
}
