//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTWeb.BettingServiceHorseRacingPlaceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BettingServiceHorseRacingPlaceReference.IBettingServiceHorseRacePlace")]
    public interface IBettingServiceHorseRacePlace {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseRacePlace/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceHorseRacePlace/GetDataFromBetfairReadOnlyRespon" +
            "se")]
        void GetDataFromBetfairReadOnly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseRacePlace/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceHorseRacePlace/GetDataFromBetfairReadOnlyRespon" +
            "se")]
        System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseRacePlace/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceHorseRacePlace/GetCurrentMarketBookCricketRespo" +
            "nse")]
        void GetCurrentMarketBookCricket(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceHorseRacePlace/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceHorseRacePlace/GetCurrentMarketBookCricketRespo" +
            "nse")]
        System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBettingServiceHorseRacePlaceChannel : GTWeb.BettingServiceHorseRacingPlaceReference.IBettingServiceHorseRacePlace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettingServiceHorseRacePlaceClient : System.ServiceModel.ClientBase<GTWeb.BettingServiceHorseRacingPlaceReference.IBettingServiceHorseRacePlace>, GTWeb.BettingServiceHorseRacingPlaceReference.IBettingServiceHorseRacePlace {
        
        public BettingServiceHorseRacePlaceClient() {
        }
        
        public BettingServiceHorseRacePlaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettingServiceHorseRacePlaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceHorseRacePlaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceHorseRacePlaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDataFromBetfairReadOnly() {
            base.Channel.GetDataFromBetfairReadOnly();
        }
        
        public System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync() {
            return base.Channel.GetDataFromBetfairReadOnlyAsync();
        }
        
        public void GetCurrentMarketBookCricket(string Password) {
            base.Channel.GetCurrentMarketBookCricket(Password);
        }
        
        public System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password) {
            return base.Channel.GetCurrentMarketBookCricketAsync(Password);
        }
    }
}
