// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace bftradeline
{

    public class Ex
    {

        [JsonProperty("availableToBack")]
        public AvailableToBack[] AvailableToBack { get; set; }

        [JsonProperty("availableToLay")]
        public AvailableToLay[] AvailableToLay { get; set; }

        [JsonProperty("tradedVolume")]
        public object[] TradedVolume { get; set; }
    }

}
