//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTWeb.BettingServiceCricketMatchOddsReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BettingServiceCricketMatchOddsReference.IBettingServiceCricketMatchOdds")]
    public interface IBettingServiceCricketMatchOdds {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketMatchOdds/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceCricketMatchOdds/GetDataFromBetfairReadOnlyResp" +
            "onse")]
        void GetDataFromBetfairReadOnly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketMatchOdds/GetDataFromBetfairReadOnly", ReplyAction="http://tempuri.org/IBettingServiceCricketMatchOdds/GetDataFromBetfairReadOnlyResp" +
            "onse")]
        System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketMatchOdds/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceCricketMatchOdds/GetCurrentMarketBookCricketRes" +
            "ponse")]
        void GetCurrentMarketBookCricket(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketMatchOdds/GetCurrentMarketBookCricket", ReplyAction="http://tempuri.org/IBettingServiceCricketMatchOdds/GetCurrentMarketBookCricketRes" +
            "ponse")]
        System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBettingServiceCricketMatchOddsChannel : GTWeb.BettingServiceCricketMatchOddsReference.IBettingServiceCricketMatchOdds, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettingServiceCricketMatchOddsClient : System.ServiceModel.ClientBase<GTWeb.BettingServiceCricketMatchOddsReference.IBettingServiceCricketMatchOdds>, GTWeb.BettingServiceCricketMatchOddsReference.IBettingServiceCricketMatchOdds {
        
        public BettingServiceCricketMatchOddsClient() {
        }
        
        public BettingServiceCricketMatchOddsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettingServiceCricketMatchOddsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceCricketMatchOddsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceCricketMatchOddsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDataFromBetfairReadOnly() {
            base.Channel.GetDataFromBetfairReadOnly();
        }
        
        public System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync() {
            return base.Channel.GetDataFromBetfairReadOnlyAsync();
        }
        
        public void GetCurrentMarketBookCricket(string Password) {
            base.Channel.GetCurrentMarketBookCricket(Password);
        }
        
        public System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password) {
            return base.Channel.GetCurrentMarketBookCricketAsync(Password);
        }
    }
}
