// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Text;

namespace bfnexchange.Services
{

    public class Runner
    {

        [JsonProperty("selectionId")]
        public int SelectionId { get; set; }

        [JsonProperty("handicap")]
        public double? Handicap { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("adjustmentFactor")]
        public double? AdjustmentFactor { get; set; }

        [JsonProperty("lastPriceTraded")]
        public double? LastPriceTraded { get; set; }

        [JsonProperty("totalMatched")]
        public double? TotalMatched { get; set; }

        [JsonProperty("ex")]
        public Ex Ex { get; set; }

        [JsonProperty("removalDate")]
        public string RemovalDate { get; set; }

        public override string ToString()
        {
            StringBuilder stringBuilder = new StringBuilder().AppendFormat("SelectionId={0}", this.SelectionId).AppendFormat(" : Handicap={0}", this.Handicap).AppendFormat(" : Status={0}", this.Status).AppendFormat(" : AdjustmentFactor={0}", this.AdjustmentFactor).AppendFormat(" : LastPriceTraded={0}", this.LastPriceTraded).AppendFormat(" : TotalMatched={0}", this.TotalMatched).AppendFormat(" : RemovalDate={0}", this.RemovalDate);

            if (this.Ex != null)
            {
                stringBuilder.AppendFormat(": {0}", this.Ex);
            }

            return stringBuilder.ToString();
        }
    }

}
