//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfnexchange.BettingServiceCricketCompletedMatchReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BettingServiceCricketCompletedMatchReference.IBettingServiceCricketCompletedMatch" +
        "")]
    public interface IBettingServiceCricketCompletedMatch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetDataFromBetfairReadOnl" +
            "y", ReplyAction="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetDataFromBetfairReadOnl" +
            "yResponse")]
        void GetDataFromBetfairReadOnly();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetDataFromBetfairReadOnl" +
            "y", ReplyAction="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetDataFromBetfairReadOnl" +
            "yResponse")]
        System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetCurrentMarketBookCrick" +
            "et", ReplyAction="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetCurrentMarketBookCrick" +
            "etResponse")]
        void GetCurrentMarketBookCricket(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetCurrentMarketBookCrick" +
            "et", ReplyAction="http://tempuri.org/IBettingServiceCricketCompletedMatch/GetCurrentMarketBookCrick" +
            "etResponse")]
        System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBettingServiceCricketCompletedMatchChannel : bfnexchange.BettingServiceCricketCompletedMatchReference.IBettingServiceCricketCompletedMatch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettingServiceCricketCompletedMatchClient : System.ServiceModel.ClientBase<bfnexchange.BettingServiceCricketCompletedMatchReference.IBettingServiceCricketCompletedMatch>, bfnexchange.BettingServiceCricketCompletedMatchReference.IBettingServiceCricketCompletedMatch {
        
        public BettingServiceCricketCompletedMatchClient() {
        }
        
        public BettingServiceCricketCompletedMatchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettingServiceCricketCompletedMatchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceCricketCompletedMatchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceCricketCompletedMatchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDataFromBetfairReadOnly() {
            base.Channel.GetDataFromBetfairReadOnly();
        }
        
        public System.Threading.Tasks.Task GetDataFromBetfairReadOnlyAsync() {
            return base.Channel.GetDataFromBetfairReadOnlyAsync();
        }
        
        public void GetCurrentMarketBookCricket(string Password) {
            base.Channel.GetCurrentMarketBookCricket(Password);
        }
        
        public System.Threading.Tasks.Task GetCurrentMarketBookCricketAsync(string Password) {
            return base.Channel.GetCurrentMarketBookCricketAsync(Password);
        }
    }
}
